# Omakase Ruby styling for Rails
# inherit_gem: { rubocop-rails-omakase: rubocop.yml }

# Add custom cops
# require_relative 'lib/bad_practice/no_well_placed_concerns'

plugins:
  - rubocop-rails
  # - rubocop-rails-omakase
  - rubocop-rspec

require:
  - './lib/bad_practice/no_well_placed_concerns.rb'

AllCops:
  NewCops: disable
  SuggestExtensions: false
  TargetRubyVersion: 3.4
  TargetRailsVersion: 8.0
  Exclude:
    - "bin/bundle"
    - "db/*.rb"

BadPractice/NoWellPlacedConcerns:
  Enabled: true
  Exclude:
    - "app/models/application_record.rb"
    - "app/models/concerns/**/*.rb"

Layout/LineLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false
